Character systems
warpfox/EB-Clone pull request #57
Opened 2018-06-08 03:57 UTC by warpfox

Integrates all the changes we did at my place the other day. I also went ahead and changed the gathering of CharacterInfos by GameManager from List to Dictionary. Also added HP/PP add and subtract methods in CharacterInfo.

2018-06-08 22:53 UTC, VirtuaBoza requested changes

2018-06-08 22:53 UTC, VirtuaBoza commented on Assets/Shared/Scripts/GameManager.cs
> +	public Dictionary <CharacterInfo, CharacterName> characters = new Dictionary <CharacterInfo, CharacterName>();
Nah, the first Type in the dictionary is the key, the second is the value. Seems to me that the CharacterName needs to be the key and the CharacterInfo the value.

2018-06-08 22:56 UTC, VirtuaBoza commented on Assets/Shared/Scripts/GameManager.cs
> +	public Dictionary <CharacterInfo, CharacterName> characters = new Dictionary <CharacterInfo, CharacterName>();
Ergo, you can get the right CharacterInfo object by using characters[CharacterName.Ness], etc.

2018-06-08 23:46 UTC, warpfox commented
Aight, check the latest commit homie

2018-06-09 00:25 UTC, VirtuaBoza approved these changes

2018-06-09 00:25 UTC, merged